import { Post } from "./post";

export const PostList:Post[]=[
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Spring Boot Proje Oluşturma",postImagePath:"https://hoserdude.files.wordpress.com/2014/10/springuniverse.png",postSummary:"Spring boot ile ilk proje oluşturma.",postContent:"test"},
    {postId:1,postTitle:"Spring Boot H2 Database",postImagePath:"https://hoserdude.files.wordpress.com/2014/10/springuniverse.png",postSummary:"Spring boot H2 database entegrasyonu ve basit crud işlemleri.",postContent:"test"},
    {postId:1,postTitle:"Angular 6 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 7 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 8 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 9 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 10 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 11 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 12 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://blog.rangle.io/content/images/2018/05/Angular_6_and_Beyond.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://blog.rangle.io/content/images/2018/05/Angular_6_and_Beyond.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://blog.rangle.io/content/images/2018/05/Angular_6_and_Beyond.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://blog.rangle.io/content/images/2018/05/Angular_6_and_Beyond.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://cdn-images-1.medium.com/max/1200/1*fGALulOUXEut16NWUShwGg.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://blog.rangle.io/content/images/2018/05/Angular_6_and_Beyond.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
    {postId:1,postTitle:"Angular 5 İlk Proje",postImagePath:"https://blog.rangle.io/content/images/2018/05/Angular_6_and_Beyond.png",postSummary:"Angular Cli ile Basit bir Angular 5 projesi oluşturma ve derleme",postContent:"test"},
]